- hosts: swarm-workers 
  gather_facts: yes
  become: yes
  become_method: sudo
  remote_user: vagrant

  tasks:
    - name: Add worker nodes
      docker_swarm:
        state: join
        advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        join_token: "{{ lookup('file', '~/shared/token') }}"
        remote_addrs: [ "192.168.56.2:2377" ]
