# This Play Configures GlusterFS Servers
- hosts: glusterfs
  gather_facts: no
  become: yes
  become_method: sudo
  remote_user: vagrant

  tasks:
    - name: Install GlusterFS
      apt:
        pkg: glusterfs-server
        state: present
        update_cache: yes

    - name: Create a Volume
      file:
        path: /gluster/volume
        state: directory
        mode: '0755'

    - name: Add Gluster Volume
      gluster_volume:
        name: test2
        state: present
        bricks: /gluster/volume
        replicas: 2
        cluster:
          - gluster1
          - gluster2
      run_once: true

    - name: Start Gluster Volume
      gluster_volume:
        name: test2
        state: started

# This Play Configures GlusterFS Clients
- hosts: swarm
  gather_facts: no
  become: yes
  become_method: sudo
  remote_user: vagrant

  tasks:
    - name: Install GlusterFS-Client
      apt:
        pkg: glusterfs-client
        state: present
        update_cache: yes

    - name: Create sharedfs dir
      file:
        path: /mnt/sharedfs
        state: directory
        mode: '0755'
