# This Play Configures GlusterFS Servers
- hosts: glusterfs
  gather_facts: no
  become: yes
  become_method: sudo
  remote_user: vagrant

  vars:
    vol_name: test2
    brick_name: /gluster/volume

  tasks:
    - name: Install GlusterFS
      apt:
        pkg: glusterfs-server
        state: present
        update_cache: yes

    - name: Create a Volume
      file:
        path: "{{ brick_name }}" 
        state: directory
        mode: '0770'

    - name: Add Gluster Volume
      gluster_volume:
        name: "{{ vol_name }}"
        state: present
        bricks: "{{ brick_name }}"
        replicas: 2
        cluster:
          - gluster1
          - gluster2
      run_once: true

    - name: Start Gluster Volume
      gluster_volume:
        name: "{{ vol_name }}"
        state: started

# This Play Configures GlusterFS Clients
- hosts: swarm
  gather_facts: no
  become: yes
  become_method: sudo
  remote_user: vagrant

  vars:
    src: gluster1:/test2
    sharedfs: /mnt/sharedfs

  tasks:
    - name: Install GlusterFS-Client
      apt:
        pkg: glusterfs-client
        state: present
        update_cache: yes

    - name: Create the shared filesystem dir
      file:
        path: "{{ sharedfs }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0777'

    - name: Mount the shared filesystem
      mount:
        src: "{{ src }}"
        path: "{{ sharedfs }}"
        state: mounted
        fstype: glusterfs
        opts: defaults,_netdev

    - name: Change ownership of directory
      file:
        path: "{{ sharedfs }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '1777'